### ISSUE TITLE
Error when taking midpoint

### ISSUE THREAD

**Issue by alocate** [ardaegeunlu/X-armed-Bandits#2]
Hi, thanks for the update. I tried running the code after just replacing the file, and now I get the following problem.

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-7-1a49343b0a54> in <module>()
     22 x_armed_bandit.set_time_horizon(max_plays=1000)
     23 x_armed_bandit.set_environment(environment_function=testFunction.draw_value)
---> 24 x_armed_bandit.run_hoo()
     25 
     26     # this is the most rewarding point explored so far after "max_plays" rounds.

~\Documents\X-armed-Bandits-master\HOO.py in run_hoo(self)
    149             # now we have selected the most promising child from the tree we had,
    150             # we can draw an arm in X from the coverings
--> 151             reward = self.selection_of_arm_from_covering(current_node_depth, current_node_in_level)
    152             self.create_children_of_node(current_node)
    153 

~\Documents\X-armed-Bandits-master\HOO.py in selection_of_arm_from_covering(self, h, i)
     71         :return: received reward.
     72         """
---> 73         subset_space = self.tree_coverings(h, i)
     74         # now we need to arbitrarily select one arm from this subset of the space.
     75         # the chosen strategy is selecting the midpoint of the subset but this can

~\Documents\X-armed-Bandits-master\Partitioner.py in halve_one_by_one(self, height, place_in_level)
     65         parent_h = height - 1
     66         parent_i = (place_in_level + 1) / 2
---> 67         parent_space = self.covering_sequence[parent_h, parent_i]
     68         #print("index = {0},{1} and parent = {2},{3}".format(height,place_in_level,parent_h,parent_i))
     69         # partition the dimension_to_be_partitioned into half.

KeyError: (0, 1.5)

**Comment by ardaegeunlu** [comment]
Hi,

The error is caused because of the floating point division at the following line,
`parent_i = (place_in_level + 1) / 2`
The above line returns 1.5 in your case and it was supposed to return 1. I assume you are running the code on python 3.x so you can just change that line to,
`parent_i = (place_in_level + 1) // 2`
to fix it(making it so called 'integer division'). The problem is I wrote the code on python 2.7 and really did not really think about this back then. 

[You can check this thread for even more info. ](https://stackoverflow.com/questions/183853/in-python-2-what-is-the-difference-between-and-when-used-for-division)


I will go over the code to see if there are any more issues with regards to this case and do the updates.

**Comment by ardaegeunlu** [comment]
I went over the code and it looks like that was the only problematic division, thanks for pointing it out 🥇

**Comment by alocate** [comment]
Hi,

awesome, this fixed it. I also thought it was this problem, my thinking was that two nodes with different "i" obviously need the same parent, so there should be a rounding somewhere.

**Comment by ardaegeunlu** [comment]
You are definitely right, I used integer division to utilize the floor round in it.
